language: node_js
node_js:
  - '8'
  - '10'
  - '12'
  - lts/*
  - node

before_install:
  - sudo add-apt-repository -y ppa:haxe/releases
  - sudo apt-get -q update
  - sudo apt-get -y install haxe

script:
  - npm run lint
  - npm run build
  - npm test
